source "https://rubygems.org"

gem "rack"
gem "sinatra"
gem "rackup"
gem "pg"
gem "sinatra-activerecord"
gem "pry"
gem "puma"
gem "rake"
gem "foreman", "~> 0.89.1"
gem "commonmarker"
gem "sanitize"
gem "dotenv"
